# Generated by Django 2.1 on 2018-08-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=30)),
                ('access_token', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
