# Generated by Django 2.1 on 2018-08-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180812_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='itle',
            new_name='title',
        ),
    ]
